# Generated by Django 4.1.6 on 2023-03-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='visible1',
            field=models.BooleanField(default='True', verbose_name='Видимость д/др. агентов'),
        ),
    ]
