# Generated by Django 4.1.6 on 2023-03-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_apartment_visible1'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='visible2',
            field=models.BooleanField(default='True', verbose_name='Видимость2 д/др. агентов'),
        ),
    ]
