# Generated by Django 4.1.6 on 2023-03-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_apartment_visible2'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='visible3',
            field=models.BooleanField(default='True', verbose_name='Видимость3 д/др. агентов'),
        ),
    ]
