# Generated by Django 4.1.6 on 2023-03-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_apartment_visible3'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='visible4',
            field=models.BooleanField(default='True', verbose_name='Видимость4 д/др. агентов'),
        ),
    ]
