# Generated by Django 4.1.6 on 2023-03-10 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_apartment_visible4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='visible1',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='visible2',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='visible3',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='visible4',
        ),
    ]
