# Generated by Django 4.1.6 on 2023-03-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_remove_apartment_visible1_remove_apartment_visible2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='floor',
            field=models.IntegerField(verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='number_of_floors',
            field=models.IntegerField(verbose_name='Этажность дома'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='room_quantity',
            field=models.IntegerField(verbose_name='Количество комнат'),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.IntegerField(verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='room',
            name='number_of_floors',
            field=models.IntegerField(verbose_name='Этажность дома'),
        ),
    ]
